# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_clk_wiz_1_1/Mblaze_clk_wiz_1_1.xci
# IP: The module: 'Mblaze_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_clk_wiz_1_1/Mblaze_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_clk_wiz_1_1/Mblaze_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_clk_wiz_1_1/Mblaze_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_clk_wiz_1_1/Mblaze_clk_wiz_1_1.xci
# IP: The module: 'Mblaze_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_clk_wiz_1_1/Mblaze_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_clk_wiz_1_1/Mblaze_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_clk_wiz_1_1/Mblaze_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
