# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MBlaze.xdc

# Block Designs: bd/Mblaze/Mblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze || ORIG_REF_NAME==Mblaze} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_microblaze_0_0/Mblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_microblaze_0_0 || ORIG_REF_NAME==Mblaze_microblaze_0_0} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_dlmb_v10_1/Mblaze_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_dlmb_v10_1 || ORIG_REF_NAME==Mblaze_dlmb_v10_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_ilmb_v10_1/Mblaze_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_ilmb_v10_1 || ORIG_REF_NAME==Mblaze_ilmb_v10_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_dlmb_bram_if_cntlr_1/Mblaze_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==Mblaze_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_ilmb_bram_if_cntlr_1/Mblaze_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==Mblaze_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_lmb_bram_1/Mblaze_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_lmb_bram_1 || ORIG_REF_NAME==Mblaze_lmb_bram_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_xbar_1/Mblaze_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_xbar_1 || ORIG_REF_NAME==Mblaze_xbar_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_auto_pc_0/Mblaze_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_auto_pc_0 || ORIG_REF_NAME==Mblaze_auto_pc_0} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_auto_pc_1/Mblaze_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_auto_pc_1 || ORIG_REF_NAME==Mblaze_auto_pc_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_microblaze_0_axi_periph_1/Mblaze_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_microblaze_0_axi_periph_1 || ORIG_REF_NAME==Mblaze_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_mdm_1_1/Mblaze_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_mdm_1_1 || ORIG_REF_NAME==Mblaze_mdm_1_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_clk_wiz_1_1/Mblaze_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_clk_wiz_1_1 || ORIG_REF_NAME==Mblaze_clk_wiz_1_1} -quiet] -quiet

# IP: bd/Mblaze/ip/Mblaze_rst_clk_wiz_1_100M_1/Mblaze_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mblaze_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==Mblaze_rst_clk_wiz_1_100M_1} -quiet] -quiet

# XDC: bd/Mblaze/Mblaze_ooc.xdc
