# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_lmb_bram_1/Mblaze_lmb_bram_1.xci
# IP: The module: 'Mblaze_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_lmb_bram_1/Mblaze_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_lmb_bram_1/Mblaze_lmb_bram_1.xci
# IP: The module: 'Mblaze_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/MicroBlaze_proj/MicroBlaze_proj.srcs/sources_1/bd/Mblaze/ip/Mblaze_lmb_bram_1/Mblaze_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
